### ISSUE TITLE
Provide a way to cancel individual subscriptions

### ISSUE THREAD

**Issue by cjihrig** [tierrun/node-sdk#13]
The docs for `cancel(org)` state:

> Immediately cancels all current and pending subscriptions for the specified org.

It would be nice to be able to cancel individual subscriptions for the org.

The use case I have in mind is:

- There are Free, Basic, and Pro plans billed monthly.
- In the course of a single month, an org moves from Free to Basic to Pro.

I would image that when the org goes to Basic, they would be subscribed to one plan. Then, when they move from Basic to Pro, the Basic subscription would be cancelled and a Pro subscription created. The issue I have with `cancel()` is that there are other billing items in play that I don't want to cancel. Maybe I am modeling this wrong - I am still wrapping my head around Tier.

**Comment by isaacs** [comment]
In that case, you can just call ``tier.subscribe(`org:${id}`, 'plan:pro@whatever')`` when they transition to the Pro plan.  (Or similarly when they transfer to Basic, or anything else.)  The start and end dates in their subscription phases will be updated appropriately.

In the most simple case, when you call subscribe, it resets the user's subscription to whatever you pass in.  When you do this with just a single plan, it cancels their previous plan and creates the new one, and Stripe handles the proration and such.

<details><summary>advanced usage stuff you might not care about...</summary>
If you _do_ want to mix and match individual features from different plans, multiple plans with addons, custom phases that transition from one plan to another at precise times, etc, you _can_ do that using `tier.schedule`, which takes an array of `Phase` objects.  So you could do something like:

```js
await tier.schedule(`org:${id}`, [
  { effective: new Date('2023-03-05T12:34:56Z'), features: ['plan:foo@1'] },
  { effective: new Date('2023-05-05T12:34:56Z'), features: ['plan:foo@2', 'plan:bar@1'] },
  { effective: new Date('2023-05-05T12:34:56Z'), features: ['plan:bar@1'] },
])
```
</details>

For probably the most common case of switching automatically between plans, having a trial period before a plan activates, you can use ``tier.subscribe(`org:${id}`, 'plan:blah@123', { trialDays: 14 })`, and that'll construct the Phases array for you automatically.

**Comment by cjihrig** [comment]
Thank you for the response. This is continued in Slack.
