### ISSUE TITLE
Bug - Passing Org Info via Subscribe Doesnt Work

### ISSUE THREAD

**Issue by ThatOneAwkwardGuy** [tierrun/node-sdk#7]
Description:
When calling subscribe, it doesn't appear that the org's information is set inside of Stripe. 

Actions to reproduce:
1. Using the Node SDK, subscribe a new customer, features can be an empty array and effective can be undefined, but set some org info such as name or email
2. Check stripe and you'll see that the customer is unnamed

Versions:
tierrun- 0.6.0
tier - 3.4.0

**Comment by isaacs** [comment]
Thanks for reporting!  Fixed on 3.4.2.
